project:
  type: book
  output-dir: C:\Users\user\Documents\DETRAN\TRI_PROJECT_DIEGO\book\docs

book:
  title: "TEORIA DE RESPOSTA AO ITEM"
  subtitle: "COM DADOS DO ENADE"
  description: "Da Descritiva à Análise Robusta"

  author:
  - name: "Mário Diego Rocha Valente"
    orcid: 0000-0001-7262-3336
    github: MarioDhiego
    affiliations:
      - name: "Universidade Federal do Pará"
      - name: "Instituto de Ciências Exatas e Naturais"
      - name: "Falculdade de Computação"
  - name: "Breno Cauã Rodrigues da Silva"
    orcid: 0009-0005-9740-2069
    github: csilv7
    affiliations:
      - name: "Universidade Federal do Pará"
      - name: "Instituto de Ciências Exatas e Naturais"
      - name: "Falculdade de Estatística"

  downloads: [pdf]
  sharing: [twitter, facebook]
  page-navigation: true
  repo-url: https://github.com/csilv7/APPLICATION_TRI_ENADE

  chapters:
    - index.qmd
    - part: "ANÁLISE DO ENADE POR CURSOS"
    - ANALYSIS_BY_COURSE/SISTEMAS_INFO.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    number-sections: true
    code-fold: true
    code-tools: true
    code-link: true
    toc-location: right
    theme:
      - cosmo
      - brand
    echo: false
    warning: false
    message: false
  pdf:
    documentclass: scrreprt
    pdf-engine: lualatex
    number-sections: true
    papersize: a4
    fontsize: 11pt
    geometry: [left=2.5cm, top=2.5cm, right=2.5cm, bottom=2.5cm]
    fig-pos: "H"
    indent: true
    header-includes: |
      \usepackage{indentfirst}
      \usepackage{latexsym,amssymb,amsmath,amsfonts}
      \usepackage{graphicx} % Figuras
      \usepackage{latexsym, amssymb, amsmath, amsfonts, amsthm} % Formatação Matemática
      \usepackage{xcolor}
      \usepackage{float, caption}
      \floatplacement{table}{H}
      \floatplacement{figure}{H}
      \captionsetup[table]{position=above}
      \captionsetup[figure]{position=below}
    echo: false
    warning: false
    message: false

lang: pt